### ISSUE TITLE
[FE] Make the initial introductory pages. 

### ISSUE THREAD

**Issue by kunxl-gg** [devlup-labs/iitj-omegle#6]
# Expected Behavior 
- Make the initial pages that introduce what the website is about
- Also finish the UI of the Google Sign In

#  Current Behavior
- Currently there is no such page
- The UI of the Google Sign In is still incomplete

# References: 
- You can take this as a reference 
https://chatroulette.com/info/

**Comment by boku13** [comment]
Interested in this issue.

**Comment by boku13** [comment]
Done.
